name: SimplePanel Builder

on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  PROJECT_NAME: "SimplePanel"

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Create ZIP Archive
        if: github.event_name == 'release'
        run: |
          zip -r ${{ env.PROJECT_NAME }}-${{ github.event.release.tag_name }}.zip build public package.json next.config.mjs .env.example pnpm-lock.yaml scripts \
          -x "node_modules/*" ".git/*" "*.md" "LICENSE" ".gitignore"

      - name: Upload release asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./${{ env.PROJECT_NAME }}-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}